# Generated by Django 4.1.4 on 2023-02-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="event_name",
            field=models.CharField(default="Test", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="imageupload",
            name="images",
            field=models.ImageField(upload_to=""),
        ),
    ]
