# Generated by Django 4.1.4 on 2023-02-05 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=30)),
                ("brand_tagline", models.CharField(max_length=100)),
                ("brand_logo", models.ImageField(upload_to="media")),
                ("brand_address", models.CharField(max_length=50)),
                ("brand_phone", models.CharField(max_length=15)),
                ("brand_email", models.EmailField(max_length=254)),
                ("instagram_profile", models.URLField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
