# Generated by Django 4.1.4 on 2023-02-17 13:03

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_id_alter_brandinfo_brand_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcDEfG7890",
                length=6,
                max_length=128,
                prefix="id_",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
